require_relative '../lib/aa'

context 'Global methods generated by Aa library' do
  before do
    class Beer; end
  end

  describe 'a.beer' do
    it 'creates an instance of Beer' do
      a.beer.should be_an_instance_of Beer
    end

    it 'is different to the one created in the past trial' do
      x = a.beer
      y = a.beer
      x.should_not equal y
    end
  end

  describe 'an.beer' do
    it 'is equivalent to use a.beer' do
      an.beer.should be_an_instance_of Beer

      x = an.beer
      y = an.beer
      x.should_not equal y
    end
  end

  describe 'the.beer' do
    it 'is the beer of the latest on you created by a.beer' do
      x = a.beer
      y = a.beer
      the.beer.should_not equal x
      the.beer.should equal y
    end
  end
end
